site_name: ServiceX
nav:
    - Home: index.md
    - Introduction: introduction.md
    - 'User Guide':
        - Getting started: user/getting-started.md
        - Specifying a request: user/requests.md
        - Outreach: user/outreach.md
    - 'Deployment Guide':
        - Deployment: deployment.md
    - 'Developer Guide':
        - Development: development.md
theme: readthedocs
